SystemMenuText = {
				1 : "Ticaret Aynasý",
				2 : "Market Tezgahý",
				3 : "Efsun Botu",
				4 : "Ünvan Sistemi",
				5 : "Biyolog Sistemi",
				6 : "Güvenlik",
				7 : "Pazar Ticaret Log",
				8 : "Toplu Nesne Ýþlemleri",
				9 : "Hýzlý Toplama",
				10 : "Biyolog",
}

loncaskorgoster = "Becerileri Gizle/Göster"
chsec = -1
zemin = "Karlý Zemin"
kapat = "Oyunu kapatýr."
pin2 = "Pini gir."
pin = "Hesap þifresi veya pin yanlýþ"
CHAT_GLOBAL="Ticaret"

DAKIKA =	"%s Dakika"
SAATVEDAKIKA =	"%s Saat ve %s Dakika"
GUNSAAT =	"%s Gün ve %s Saat"

itemkilit="Kilitli itemi satýþa koyamazsýnýz."
gameoptiontitle="Performans Seçenekler"
no_empty_incube = "Panelde boþ yer kalmamýþ !"

MORPOTTITLE="Yeþ./Morpot Efekti"
MORPOTACIK="Yeþil/Morpot efekti aktif. "
MORPOTKAPALI="Yeþil/Mor pot efekti deaktif."

KRITIKTITLE="Delici/Kritik Efekti"
KRITIKACIK="Delici/Kritik efekti aktif."
KRITIKKAPALI="Delici/Kritik efekti deaktif."

nesnemarket="Nesne marketimizi ziyaret ettiniz mi?"
hesapguvenlik="Hesap þifrenizi kimseyle paylaþmayýn!"
itemciticaret="TL karþýlýðý nesne ya da karakter satýþýnda IP üzerinden süresiz cezalarla karþýlaþabilirsiniz."
facebook="Fb Adresimiz: http://www.fb.com/Warder2Official "
GECMIS = "Pazar Geçmiþi"
YENILEGEC = "Pazar Geçmiþini Yenile"
YENILE1DK = "Pazar geçmiþini 1 dakikada bir yenileyebilirsin."
YANGKAR = " Yang ve "
WONKAR = " Won karþýlýðýnda |r"
TICYENILE = "Ticaret geçmiþini 1 dakikada bir yenileyebilirsin."
biyologsuresi="Biyolog süreniz dolmuþtur."
biyologyenigorev=" Lv. Biyolog Görevinize baþlayabilirsiniz."
bildirim="%s"
onlineaktif="%s Çevrimiçi."
guvenlipc="Bu bilgisayardan giriþ yapamazsýn."
baslangicengel="Uzgunum, Bunu bu itemlerde yapamazsýn!"
pencereacik="Pencere açýk kalsýn"
tic_log = "     [ %s %s ]   ----   %s  <----->  %s"
tic_gecmis = "Ticaret Geçmiþi"
tic_yenile = 'Ticaret Gecmiþini Yenile'
epsor="Ep kuponu açmak istiyor musun?"
esyakilitlendi = "Eþya kilitlendi."
esyakilitkaldirildi = "Eþyanýn kilidi kaldýrýldý."
esyayenisfire = "Yeni eþya þifresi: "
esyakilitsifreolustur = "Þifreniz oluþturulmuþtur: "
esyasifredegis = "Envanter Kilit Þifresi Deðiþtir"
esyakitle = "Eþya Kitleme"
esyakitle2 = "Eþyayý kilidin üstüne sürükleyin."
esyakitle3 = "Eþya Kilitle"
esyakitle4 = "þifreyi gir."
esyakitle5 = "Þifre minimum 6"
esyakitle6 = "maksimum 8 hane"
esyakitle7 = "olabilir."
esyakitle8 = "Eþya Kilit Aç"
esyakitle9 = "Eþyanýn kilidini açmak için"
esyakitle10 = "Þifreni unuttuysan"
esyakitle11 = "destek sistemine"
esyakitle12 = "baþvur."
esyakitle13 = "Eþyayý kilitlemek için"
esyakitle14 = "Bu eþyayý kilitlemek istediðine emin misin? Eðer þifreni"
esyakitle15 = "kaybedersen, kayýt olurken verdiðin bilgilerle þifremi unuttum yapabilirsin."
esyakitle16 = "Gereken bilgiler: Cep Telefonu, Email, Güvenlik Sorusu ve Cevabý."
yazi1 = "Güvenlik þifrenizi unuttuysanýz"
yazi2 = "oyunumuzun sitesinden sýfýrlama"
PASSWORD_DESC_1="Depoyu açmak için,"
PASSWORD_DESC_2="þifreni gir."
PASSWORD_DESC_3="Þifreni deðiþtirdin mi?"
PASSWORD_DESC_4="Deðiþtirmediysen þifren þudur: '000000'."
PASSWORD_DESC_5="Þifreni Mutlaka deðiþtir."
PASSWORD_DESC_1_1="Güvenlik kilidini açmak"
PASSWORD_DESC_2_2="için þifreyi gir."
PASSWORD_DESC_3_3="Þifreni deðiþtirdin mi?"
PASSWORD_DESC_4_4="Deðiþtirmediysen þifren þudur: '123456'."
PASSWORD_DESC_5_5="Þifreni Mutlaka deðiþtir."
PASSWORD_DESC_6_6="Deðiþtirmediysen þifren '123456'dýr."
olustur1 = "|cFF00CCFFSistem Hakkýnda|r"
olustur2 = "|cFFe7de0eÝçin Oluþturulan Þifredir|r"
yazi3 = "isteði gönderebilirsiniz."
yazi4 = ""
yazi5 = "Güvenlik sistemi hesabýnýzý"
yazi6 = "güvende tutmak için hazýrlanmýþtýr."
yazi7 = "Kullanýp kullanmama hakkýna sahipsiniz."
yazi8 = "Sistem kilidi açýlana kadar karakterin"
yazi9 = "yapabileceði tek þey þifre girmektir."
yazi10 = "Sistemi kapatmak/açmak veya"
yazi11 = "þifrenizi deðiþtirmek istiyorsanýz"
yazi12 = "hýzlý menüden kilit iconuna"
yazi13 = "týklayýp ayarlara ulaþabilirsiniz."
yazi14 = "Not: Sistem aktif edildiðinde"
yazi15 = "þifreniz yine ayný kalýr."
unuttum = "|cFFe7de0eUnuttum ?|r"
unuttum2 = "|cFF0ea930Þifre Sýfýrlama Bilgileri|r"
PASSWORD_TITLE="Güvenlik Þifresi"
bilgilendirmechat="TL karþýlýðý nesne ya da karakter satýþýnda IP üzerinden süresiz cezalarla karþýlaþabilirsiniz."
evokilit = "Kilitli itemi evrimleþtiremezsin."
EVOLUTION_SUCCESS_PROBALITY="Evrim Þansý %d%%"
EVOLUTION_GOLD="Evrim Ücret: %d Yang"
EVOLUTION_WARNING = "Evrim geliþtiriliyor, baþarýsýz olabilir."
EVOLUTION_SUCCESS="Evrim geliþimi baþarýlý !"
EVOLUTION_FAILURE="Evrim geliþimi baþarýsýz."
sadecesilah = "Sadece silahlar evrimleþtirilebilir."
acik = 0
chpanel = "Yan Panel"
acbut = "Göster"
kapbut = "Gizle"
inventoryPageIndex=1
inventoryPageIndexo=0
yenile=0
guvenlikbaslik="Güvenlik Þifresi"
gir="Güvenlik Þifre:"
sifredegis="Þ.Deðiþtir"
sifredegis1="Þ.Deðiþtir"
barsor="Barý kullanmak istiyor musun?"
baglidepo="Baðlý eþyayý depoya koyamazsýn."
lessystem = "[Leþ Sayýsý: %s]"
baslangic = "[Baþlangýçta Açýlabilir.]"
baglidepo="Baðlý eþyayý depoya koyamazsýn."
bagli = "|cFFDC143C[Baðlý]|r"
kisimax="<Kiþi> En az: 2 -- En fazla: 100"
kisimax2="Katýlýmcý en az 2 en fazla 100 olabilir !"
OPEN="Açýk"
CLOSE="Kapalý"
observer_mode="Ýzleyici Giriþi"
olme_oldurme="Ölme: %s Öldürme: %s"
atalim_mi="%s isimli oyuncunun ajan olma þansý var."
savas_ajan="Savaþtan atýlsýn mý?"
pazarmenu="Pazar"
esyaramamenu="Eþya Arama"
efsunmenu="Efsun Botu"
guvenlikmenu="Guvenlik"
hizlimenu="Hýzlý Ekipman"
logmenu="Log Kayýtlarý"
esyamenu="Eþya Toplama"
tammenu="Tam Ekran"
uzakmenu="Uzaktan Market"
rutbemenu="Rutbe"
